- hosts: "{{ server_ip }}"
  remote_user: "{{ server_user }}"
  vars_files:
    - vars/main.yml
  vars:
    database_name: "{{ database_name }}"
    database_user: "{{ database_user }}"
    database_password: "{{ database_password }}"
    apache_listen_port: "{{ apache_port }}"
    mysql_root_password: "{{ mysql_root_password }}"
  roles:
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.nginx
    - geerlingguy.certbot
  post_tasks:
    - name: Install Varnish
      include: tasks/varnish-configuration.yml
      when: varnish_listen_port != "0"
    - name: Post tasks
      include: tasks/post-install.yml
