- name: Create the database of the website
  mysql_db:
    name: "{{ database_name }}"
    state: present
    encoding: "utf8mb4"
    collation: "utf8mb4_unicode_ci"
- name: Create database user with name and password with the drupal privileges
  mysql_user:
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    priv: '{{ database_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,CREATE TEMPORARY TABLES,LOCK TABLES'
    state: present
