- name: Setup apache config for the website
  template: src=templates/conf/apache/project.conf dest=/etc/apache2/sites-available/{{ drupal_domain }}.conf
- name: Activate vhost
  file: src=/etc/apache2/sites-available/{{ drupal_domain }}.conf dest=/etc/apache2/sites-enabled/{{ drupal_domain }}.conf state=link
- name: Restart apache
  service: name=apache2 state=restarted enabled=yes
- name: Remove default vcl
  file: path=/etc/varnish/default.vcl
        state=absent
- name: Create varnish VCL
  template: src=templates/conf/varnish/default.vcl dest=/etc/default/varnish/default.vcl
  when: ansible_os_family != "Debian"
