- name: Install other system packages that will be used to manage the server.
  apt:
    pkg: "{{ packages }}"
    state: present
  when: ansible_os_family == 'Debian'
  vars:
    packages:
      - vim
      - zip
      - wget
      - apt-transport-https
- name: Enable apache modules
  shell: a2enmod rewrite expires headers
- name: Restart apache
  service: name=apache2 state=restarted enabled=yes
