- name: Install Varnish
  apt: name=varnish state=present
  when: varnish_listen_port != "0"
  ignore_errors: yes

- service:
    name: varnish
    state: stopped
  when: varnish_listen_port != "0"

- name: Remove default varnish file
  file: path=/etc/default/varnish
        state=absent
  when: ansible_os_family != "Debian"

- name: Create varnish file to listen to the configured port
  template: src=templates/conf/varnish/varnish dest=/etc/default/varnish
  when: ansible_os_family != "Debian"

- name: Remove varnish.service
  file: path=/lib/systemd/system/varnish.service
        state=absent
  when: ansible_os_family == "Debian"

- name: Generate new varnish.service for Debian systems
  template: src=templates/conf/varnish/varnish.service dest=/lib/systemd/system/varnish.service
  when: ansible_os_family == "Debian"

- name: Remove default vcl
  file: path=/etc/varnish/default.vcl
        state=absent

- name: Create the varnish vcl
  template: src=templates/conf/varnish/default.vcl dest=/etc/varnish/default.vcl

- name: Reload daemon
  shell: systemctl daemon-reload && systemctl restart varnish.service
  notify:
  - restart varnish
